// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/comments_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/comments_service.go -destination=internal/service/mock/comments_service_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	models "github.com/mrhumster/comments-service/internal/domain/models"
	service "github.com/mrhumster/comments-service/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockCommentsService is a mock of CommentsService interface.
type MockCommentsService struct {
	ctrl     *gomock.Controller
	recorder *MockCommentsServiceMockRecorder
	isgomock struct{}
}

// MockCommentsServiceMockRecorder is the mock recorder for MockCommentsService.
type MockCommentsServiceMockRecorder struct {
	mock *MockCommentsService
}

// NewMockCommentsService creates a new mock instance.
func NewMockCommentsService(ctrl *gomock.Controller) *MockCommentsService {
	mock := &MockCommentsService{ctrl: ctrl}
	mock.recorder = &MockCommentsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommentsService) EXPECT() *MockCommentsServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCommentsService) Create(ctx context.Context, actor service.Actor, streamID uuid.UUID, parentID *uuid.UUID, rawBody string) (*models.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, actor, streamID, parentID, rawBody)
	ret0, _ := ret[0].(*models.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCommentsServiceMockRecorder) Create(ctx, actor, streamID, parentID, rawBody any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCommentsService)(nil).Create), ctx, actor, streamID, parentID, rawBody)
}

// Delete mocks base method.
func (m *MockCommentsService) Delete(ctx context.Context, actor service.Actor, commentID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, actor, commentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCommentsServiceMockRecorder) Delete(ctx, actor, commentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCommentsService)(nil).Delete), ctx, actor, commentID)
}

// ListReplies mocks base method.
func (m *MockCommentsService) ListReplies(ctx context.Context, parentID uuid.UUID, limit int, cursor *service.Cursor) ([]*models.CommentView, *service.Cursor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReplies", ctx, parentID, limit, cursor)
	ret0, _ := ret[0].([]*models.CommentView)
	ret1, _ := ret[1].(*service.Cursor)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListReplies indicates an expected call of ListReplies.
func (mr *MockCommentsServiceMockRecorder) ListReplies(ctx, parentID, limit, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReplies", reflect.TypeOf((*MockCommentsService)(nil).ListReplies), ctx, parentID, limit, cursor)
}

// ListTop mocks base method.
func (m *MockCommentsService) ListTop(ctx context.Context, streamID uuid.UUID, limit int, cursor *service.Cursor) ([]*models.CommentView, *service.Cursor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTop", ctx, streamID, limit, cursor)
	ret0, _ := ret[0].([]*models.CommentView)
	ret1, _ := ret[1].(*service.Cursor)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTop indicates an expected call of ListTop.
func (mr *MockCommentsServiceMockRecorder) ListTop(ctx, streamID, limit, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTop", reflect.TypeOf((*MockCommentsService)(nil).ListTop), ctx, streamID, limit, cursor)
}

// Update mocks base method.
func (m *MockCommentsService) Update(ctx context.Context, actor service.Actor, commentID uuid.UUID, rawBody string) (*models.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, actor, commentID, rawBody)
	ret0, _ := ret[0].(*models.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCommentsServiceMockRecorder) Update(ctx, actor, commentID, rawBody any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCommentsService)(nil).Update), ctx, actor, commentID, rawBody)
}
