// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/comment_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/comment_repository.go -destination=internal/repository/mock/comment_repository_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	models "github.com/mrhumster/comments-service/internal/domain/models"
	gomock "go.uber.org/mock/gomock"
)

// MockCommentRepository is a mock of CommentRepository interface.
type MockCommentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCommentRepositoryMockRecorder
	isgomock struct{}
}

// MockCommentRepositoryMockRecorder is the mock recorder for MockCommentRepository.
type MockCommentRepositoryMockRecorder struct {
	mock *MockCommentRepository
}

// NewMockCommentRepository creates a new mock instance.
func NewMockCommentRepository(ctrl *gomock.Controller) *MockCommentRepository {
	mock := &MockCommentRepository{ctrl: ctrl}
	mock.recorder = &MockCommentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommentRepository) EXPECT() *MockCommentRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCommentRepository) Create(ctx context.Context, comment *models.Comment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, comment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCommentRepositoryMockRecorder) Create(ctx, comment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCommentRepository)(nil).Create), ctx, comment)
}

// Delete mocks base method.
func (m *MockCommentRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCommentRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCommentRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockCommentRepository) GetByID(ctx context.Context, id uuid.UUID) (*models.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCommentRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCommentRepository)(nil).GetByID), ctx, id)
}

// ListByStream mocks base method.
func (m *MockCommentRepository) ListByStream(ctx context.Context, streamID uuid.UUID, limit int, beforeCreatedAt *time.Time, beforeID *uuid.UUID) ([]*models.CommentView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByStream", ctx, streamID, limit, beforeCreatedAt, beforeID)
	ret0, _ := ret[0].([]*models.CommentView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByStream indicates an expected call of ListByStream.
func (mr *MockCommentRepositoryMockRecorder) ListByStream(ctx, streamID, limit, beforeCreatedAt, beforeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByStream", reflect.TypeOf((*MockCommentRepository)(nil).ListByStream), ctx, streamID, limit, beforeCreatedAt, beforeID)
}

// ListReplies mocks base method.
func (m *MockCommentRepository) ListReplies(ctx context.Context, parentID uuid.UUID, limit int, afterCreatedAt *time.Time, afterID *uuid.UUID) ([]*models.CommentView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReplies", ctx, parentID, limit, afterCreatedAt, afterID)
	ret0, _ := ret[0].([]*models.CommentView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListReplies indicates an expected call of ListReplies.
func (mr *MockCommentRepositoryMockRecorder) ListReplies(ctx, parentID, limit, afterCreatedAt, afterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReplies", reflect.TypeOf((*MockCommentRepository)(nil).ListReplies), ctx, parentID, limit, afterCreatedAt, afterID)
}

// UpdateBody mocks base method.
func (m *MockCommentRepository) UpdateBody(ctx context.Context, id uuid.UUID, body string, now time.Time) (*models.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBody", ctx, id, body, now)
	ret0, _ := ret[0].(*models.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBody indicates an expected call of UpdateBody.
func (mr *MockCommentRepositoryMockRecorder) UpdateBody(ctx, id, body, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBody", reflect.TypeOf((*MockCommentRepository)(nil).UpdateBody), ctx, id, body, now)
}
